[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf8-read = "0.4.0"
log = "0.4.21"
futures = { version = "0.3.30", features = ["thread-pool"] }
threadpool = "1.8.1"
